experiment_config: experiment_simulation_only_beers_wavelength.yaml
env_config:        env_beers_wavelength_concrete.yaml
model_config:      model_mock_vlm.yaml
prompt_config:     prompt_simulation_only.yaml